### ISSUE TITLE
stream stop after ~1.5sec

### ISSUE THREAD

**Issue by kylox** [livio/sdl_video_streaming_android_sample#10]
Hi !

I tried to use this android application with a gstreamer graph on my board (I'm using USB between the phone and the board). 
I use the smartdevicelink/generic_hmi (master branch) and sdl-core (release/4.1_LTS commit:5043a62)
My stream goes through the video_stream_pipe and gstreamer start playing but after approximately 1.5 sec gstreamer received an EOS and stop

In the result I just got the first 1.5 sec of the sdl.mp4

I don't really know where this could come from

**Comment by BrettyWhite** [comment]
Its going to be difficult for us to help debug on such an old version of core, is there a chance you could try on a more recent version? 4.1 was released in 2016.

**Comment by kylox** [comment]
Yes I could try on a more recent I was using the version from AGL (meta-sdl)

**Comment by BrettyWhite** [comment]
Ya unfortunately we mainly build and test on main-line SDL, I am not familiar with meta-sdl. Give that a try and let me know how it goes. We also have a pretty good community on slack http://slack.smartdevicelink.com/ so feel free to chat there if you want, this would probably go best in the #core-help or #android-help channels, as its easier than using github issues.

**Comment by kylox** [comment]
Yes I'll give it a try ! thanks for the information I'll join the slack

**Comment by joeygrover** [comment]
This is likely related to an issue on Core/HMI. The default pair has a pop up that displays `Would you like to start the stream`. If you don't press `Yes`, the stream will be closed at the time interval you are seeing. Therefore I do not believe this is an issue with the app, but specific to Core/HMI and will be closing the issue.

**Comment by Jack-Byrne** [comment]
@kylox I am not sure the generic HMI has the correct RPCs implemented to handle starting a video stream. Please try this hmi to see if it solves any issues. https://github.com/smartdevicelink/sdl_hmi

**Comment by kylox** [comment]
@joeygrover thanks for the information

@JackLivio humm I tried to used the sdl_hmi but the stream won't start, the app is recognize but I don't pass in the onOnHMIStatus which start the stream (and the hmi is not running well on my platform)
